<?php

namespace ReclamationBundle\Repository;

/**
 * MapLocationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MapLocationRepository extends \Doctrine\ORM\EntityRepository
{
}
