<?php

namespace EshopBundle\Repository;

/**
 * CategorieERepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieERepository extends \Doctrine\ORM\EntityRepository
{
    public function countProductsThatBelongsToThisCategory($val)
    {
        $arr=$this->getEntityManager()
            ->createQuery(
                ' SELECT count(a.id) FROM  EshopBundle:Produit a '
            )
            ->getSingleScalarResult();


        return $arr;
    }
}
