<?php

namespace EshopBundle\Repository;
/**
 * CommandeERepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeERepository extends \Doctrine\ORM\EntityRepository
{
    public function lastID()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p 
                FROM EshopBundle:CommandeE p ORDER BY p.id DESC '
                )
            ->setMaxResults(1)->getResult();
    }
}
