<?php

namespace EshopBundle\Repository;

/**
 * CommandeERepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeERepository extends \Doctrine\ORM\EntityRepository
{
}
