<?php

namespace EshopBundle\Repository;

/**
 * LigneCommandeERepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LigneCommandeERepository extends \Doctrine\ORM\EntityRepository
{


    public function getBiggestIDCommandInLigneCommande()
    {
        $all= $this->getEntityManager()
            ->createQuery(
                "SELECT p
                FROM EshopBundle:LigneCommandeE p ORDER BY p.id DESC
                    ")->setMaxResults(1)->getResult();
        return $all;

    }
    /******************************************************/
        public function findByCmdId()
        {
            $all=$this->getBiggestIDCommandInLigneCommande();
            $val=$all[0];
            $dep= $this->getEntityManager()
                ->createQuery(
                    'SELECT  p
                FROM EshopBundle:LigneCommandeE p
                WHERE p.idCommande = :str'
                )
               ->setParameter('str', $val->getIdCommande())
                ->getResult();
            return $dep;
        }
        /**************************************/
        public function findCorrespondantProduct($val)
        {


            return $this->getEntityManager()
                    ->createQuery(
                        'SELECT p
                FROM EshopBundle:ProduitE p
                WHERE p.id = :str'
                    )
                    ->setParameter('str', $val)
                    ->getResult();

        }
        /***********************************************/
        public function findAllProducts()
        {
            $list=$this->findByCmdId();
            $myArray= array();

            foreach($list as $l )
            {
                $val=$l->getIdProduit();
                $myVal = $this->findCorrespondantProduct($val);
                array_push($myArray,$myVal[0]);
            }
            return $myArray;
        }
    /***********************************************/

}
