<?php

namespace EshopBundle\Repository;

/**
 * ProduitERepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitERepository extends \Doctrine\ORM\EntityRepository
{
}
