<?php

namespace EshopBundle\Repository;

/**
 * testERepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class testERepository extends \Doctrine\ORM\EntityRepository
{
}
