<?php

namespace RestoBundle\Repository;

/**
 * abonnerestoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class abonnerestoRepository extends \Doctrine\ORM\EntityRepository
{
    public function findMyReservations($person)
    {
        $query = $this->getEntityManager()->createQuery(" SELECT r FROM RestoBundle:abonneresto r WHERE r.idAb
        
        ='$person'");
        return $query->getResult();
    }

    public function findMesEnfants($person)
    {
        $query = $this->getEntityManager()->createQuery(" SELECT r FROM RestoBundle:abonneresto r WHERE r.idAb
        
        ='$person'");
        return $query->getResult();
    }

    public function verifierExiste($idAb,$nom)
    {
      /*  $qb = $this->createQueryBuilder('ab');
        $qb->where('ab.idAb=:idAb');
        $qb->andWhere('ab.nom=:nom');
        $qb->setParameter('idAb', $idAb);
        $qb->setParameter('nom',$nom);
        return $qb->getQuery()->getResult();*/

        $query = $this->getEntityManager()->createQuery(" SELECT r FROM RestoBundle:abonneresto r WHERE r.idAb
        
        ='$idAb' and r.nom='$nom' ");
        return $query->getResult();


    }


}
