<?php

namespace RestoBundle\Repository;

/**
 * cartefideliteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class cartefideliteRepository extends \Doctrine\ORM\EntityRepository
{

    public function verifierExiste($idAb)
    {
        $qb = $this->createQueryBuilder('cf');
        $qb->where('cf.idAb=:idAb');
        $qb->setParameter('idAb', $idAb);
        return $qb->getQuery()->getResult();


    }
    public function findMyCarte($person)
    {
        $query = $this->getEntityManager()->createQuery(" SELECT r FROM RestoBundle:cartefidelite r WHERE r.idAb
        
        ='$person'");
        return $query->getResult();
    }
}
