<?php

namespace RestoBundle\Repository;

use Symfony\Component\HttpFoundation\Request;
use RestoBundle\Entity\Plat;
use RestoBundle\Entity\Plats;


/**
 * PlatsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlatsRepository extends \Doctrine\ORM\EntityRepository
{



}
