dorsaf_event:
    resource: "@DorsafBundle/Controller/EventController.php"
    type:     annotation

dorsaf_club:
    resource: "@DorsafBundle/Controller/ClubController.php"
    type:     annotation

dorsaf:
    resource: "@DorsafBundle/Resources/config/routing.yml"
    prefix:   /

ichh:
    resource: "@ichhBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

adesigns_calendar:
    resource: "@ADesignsCalendarBundle/Resources/config/routing.xml"

ancarebeca_fullcalendar:
    resource: "@FullCalendarBundle/Resources/config/routing.yml"
