esprit_api:
    resource: "@EspritApiBundle/Resources/config/routing.yml"
    prefix:   /

eshop:
    resource: "@EshopBundle/Resources/config/routing.yml"
    prefix:   /

ichh:
    resource: "@ichhBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

esprit_api:
    resource: "@EspritApiBundle/Resources/config/routing.yml"
    prefix: /api