paiement_index:
    path:     /
    defaults: { _controller: "RestoBundle:paiement:index" }
    methods:  GET

paiement_indexAdmin:
    path:     /indexAdmin
    defaults: { _controller: "RestoBundle:paiement:indexAdmin" }
    methods:  GET

paiement_show:
    path:     /{id}/show
    defaults: { _controller: "RestoBundle:paiement:show" }
    methods:  GET

paiement_new:
    path:     /new
    defaults: { _controller: "RestoBundle:paiement:new" }
    methods:  [GET, POST]

paiement_edit:
    path:     /{id}/edit
    defaults: { _controller: "RestoBundle:paiement:edit" }
    methods:  [GET, POST]

paiement_delete:
    path:     /{id}/delete
    defaults: { _controller: "RestoBundle:paiement:delete" }
    methods:  DELETE

notification:
    path:     /notification
    defaults: { _controller: "RestoBundle:paiement:sendNotification" }

paiement_ajouterMobile:
    path:     /newMobile
    defaults: { _controller: "RestoBundle:paiement:AjouterMobile" }

paiement_afficherMobile:
    path:     /AfficherMobile
    defaults: { _controller: "RestoBundle:paiement:AfficherMobile" }